import type { Metadata } from "next";
import { Barlow, Fraunces, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geistBarlow = Barlow({
  variable: "--font-geist-barlow",
  subsets: ["latin"],
  weight: '600'
});

const geistFraunces = Fraunces({
  variable: "--font-geist-fraunces",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Sunshine Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistBarlow.variable} ${geistFraunces.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
